<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NewFolder\**" />
    <Content Remove="NewFolder\**" />
    <EmbeddedResource Remove="NewFolder\**" />
    <None Remove="NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="wwwroot\Template\fonts\.vs\fonts\v17\DocumentLayout.json" />
    <Content Include="wwwroot\Template\fonts\.vs\VSWorkspaceState.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
    <PackageReference Include="X.PagedList" Version="10.2.1" />
    <PackageReference Include="X.PagedList.Mvc.Core" Version="10.2.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Template\fonts\.vs\fonts\FileContentIndex\b85b2e2b-e996-417e-aea5-03a78eed7eef.vsidx" />
    <None Include="wwwroot\Template\fonts\.vs\slnx.sqlite" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Data\" />
  </ItemGroup>

</Project>
